services:
  backend:
    build:
      context: .
      dockerfile: ai-services/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: panel-pachi/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
